# Generated by Django 2.2.7 on 2019-11-25 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20190319_1131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listitem',
            options={'ordering': ['order', 'id'], 'verbose_name': 'list item'},
        ),
        migrations.AlterModelOptions(
            name='profilemember',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='listitem',
            name='order',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='profilemember',
            name='order',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
