# Generated by Django 2.2.7 on 2020-01-16 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20191125_1222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['order', 'created_date']},
        ),
        migrations.AddField(
            model_name='page',
            name='order',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
