# Generated by Django 2.2.7 on 2019-11-11 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
