# Generated by Django 2.1.5 on 2019-03-09 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_content_events'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hero',
            options={'verbose_name': 'hero', 'verbose_name_plural': 'heroes'},
        ),
    ]
