# Generated by Django 2.1.5 on 2019-03-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listitem',
            options={'ordering': ['id'], 'verbose_name': 'list item'},
        ),
        migrations.AlterModelOptions(
            name='profilemember',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='profilemember',
            name='role',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
