# Generated by Django 3.2.1 on 2021-05-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20191125_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='embed',
            name='align',
            field=models.CharField(blank=True, choices=[('', 'Default'), ('responsive', 'Responsive'), ('fullSize', 'Full size')], default='', help_text="(Leave blank unless you know what you're doing!)", max_length=200),
        ),
    ]
